server:
  port: 8085

spring:
  application:
    name: virtual-waiting-room
  datasource:
    url: jdbc:mysql://localhost:3306/virtual_waiting_room
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hikari-pool
      minimum-idle: 5  #最小空闲连接
      maximum-pool-size: 20 #最大连接数
      connection-timeout: 30000  #数据库连接超时时间，ms
      idle-timeout: 600000  #空闲连接存活最大时间，ms
      max-lifetime: 1780000  #池中连接最长生命周期，值0表示无限生命周期，ms
      auto-commit: false  #池返回的连接的默认自动提交行为,默认值：true
  redis:
    host: localhost
    port: 6379
    password: 123456

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.zcn.virtual.waiting.room.infrastructure.repository.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: cn.zcn.virtual.waiting.room.infrastructure.repository.typeHandler.EnumValueTypeHandler

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

rocketmq:
  name-server: 0.0.0.0:9876
  producer:
    send-message-timeout: 5000
    group: "virtual-waiting-room"
